-- Migration 038: Create user_notifications table for internal CRM notifications
-- Target: Supabase Postgres

BEGIN;

CREATE TABLE IF NOT EXISTS public.user_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  event_type VARCHAR(50) NOT NULL,
  type VARCHAR(50),
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  entity_type VARCHAR(50),
  entity_id BIGINT,
  action_url VARCHAR(500),
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  dedupe_key VARCHAR(255) UNIQUE,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for performance and deduplication
CREATE INDEX IF NOT EXISTS idx_user_notifications_user_id_created ON public.user_notifications (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_notifications_user_unread ON public.user_notifications (user_id, is_read) WHERE is_read = FALSE;
CREATE INDEX IF NOT EXISTS idx_user_notifications_entity ON public.user_notifications (entity_type, entity_id);

-- PostgreSQL Row Level Security (RLS) & Role Permissions
ALTER TABLE public.user_notifications ENABLE ROW LEVEL SECURITY;

-- Deny direct access to public roles (anon and authenticated)
REVOKE ALL ON public.user_notifications FROM PUBLIC, anon, authenticated;

-- Grant full access to backend service_role only
GRANT ALL ON public.user_notifications TO service_role;

COMMIT;
