import {describe,it,expect,beforeAll,afterAll} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
let db;
beforeAll(async()=>{
  db=new PGlite();
  await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE TABLE users(id bigint PRIMARY KEY,role text,is_active integer); INSERT INTO users VALUES(1,'ADMIN',1),(2,'MANAGER',1);
    CREATE TABLE projects(id bigint PRIMARY KEY,code text); INSERT INTO projects VALUES(1,'TZ');
    CREATE TABLE buildings(id bigint PRIMARY KEY,project_id bigint,name text);INSERT INTO buildings VALUES(1,1,'A');
    CREATE TABLE sections(id bigint PRIMARY KEY,building_id bigint);INSERT INTO sections VALUES(1,1);
    CREATE TABLE floors(id bigint PRIMARY KEY,section_id bigint);INSERT INTO floors VALUES(1,1);
    CREATE TABLE units(id bigint PRIMARY KEY,floor_id bigint,unit_number text);INSERT INTO units VALUES(1,1,'7');
    CREATE TABLE deals(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,unit_id bigint,contract_number text,deal_date date);
    CREATE TABLE payments(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,reference text,payment_date date,amount_minor integer);
    CREATE TABLE expenses(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,reference text,expense_date date,amount_minor integer);
    INSERT INTO deals VALUES(100,1,'OLD-100','2026-01-01');INSERT INTO payments VALUES(100,'ПКО-100','2026-01-01',123456);INSERT INTO expenses VALUES(100,'РКО-100','2026-01-01',10000);
    GRANT SELECT ON users TO service_role; GRANT INSERT,SELECT ON deals,payments,expenses TO anon; GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO anon;
  `);
  await db.exec(readFileSync(new URL('../../db/migrations/20261008190907_document_templates.sql',import.meta.url),'utf8'));
  await db.exec(readFileSync(new URL('../../db/migrations/20261008192509_document_settings_service_policies.sql',import.meta.url),'utf8'));
});
afterAll(async()=>db.close());
describe.sequential('private settings and transactional numbering',()=>{
  it('denies direct anonymous configuration reads',async()=>{
    await db.exec('SET ROLE anon');try{await expect(db.query('SELECT * FROM crm_document_settings')).rejects.toThrow();}finally{await db.exec('RESET ROLE');}
  });
  it('updates configuration as active admin, keeps history, rejects stale or other actors',async()=>{
    await db.exec('SET ROLE service_role');try{
      await db.query(`SELECT save_crm_document_settings(1,1,'{"numbering":{"CONTRACT":"{project_code}-{year}-{id4}-{unit}","PKO":"ПКО-{year}-{id4}","RKO":"РКО-{id4}"}}')`);
      await expect(db.query(`SELECT save_crm_document_settings(1,1,'{}')`)).rejects.toThrow('STALE_SETTINGS');
      await expect(db.query(`SELECT save_crm_document_settings(2,2,'{}')`)).rejects.toThrow('ADMIN_REQUIRED');
      expect((await db.query('SELECT * FROM crm_document_settings_history')).rows).toHaveLength(1);
    }finally{await db.exec('RESET ROLE');}
  });
  it('assigns numbers through legacy inserts without exposing settings or changing references',async()=>{
    await db.exec('SET ROLE anon');try{
      const d=(await db.query(`INSERT INTO deals(id,unit_id,contract_number,deal_date) VALUES(101,1,'legacy-generated','2026-10-09') RETURNING *`)).rows[0];
      expect(d.contract_number).toBe('TZ-2026-0101-7');
      const p=(await db.query(`INSERT INTO payments(id,reference,payment_date,amount_minor) VALUES(101,'ПКО-ПЕРЕМ-101','2026-10-09',8765) RETURNING *`)).rows[0];
      expect(p.document_number).toBe('ПКО-2026-0101');expect(p.reference).toBe('ПКО-ПЕРЕМ-101');expect(p.amount_minor).toBe(8765);
      const e=(await db.query(`INSERT INTO expenses(id,reference,expense_date,amount_minor) VALUES(101,'РКО-ПЕРЕМ-101','2026-10-09',4567) RETURNING *`)).rows[0];expect(e.document_number).toBe('РКО-0101');expect(e.reference).toBe('РКО-ПЕРЕМ-101');
    }finally{await db.exec('RESET ROLE');}
  });
  it('never modifies previously issued documents',async()=>{
    expect((await db.query('SELECT * FROM deals WHERE id=100')).rows[0].contract_number).toBe('OLD-100');
    expect((await db.query('SELECT * FROM payments WHERE id=100')).rows[0]).toMatchObject({document_number:null,reference:'ПКО-100',amount_minor:123456});
  });
  it('keeps only one active revision and can restore historical version',async()=>{
    await db.exec('SET ROLE service_role');try{
      const rows=(await db.query(`INSERT INTO crm_document_templates(kind,language,name,file_base64,file_size,created_by) VALUES('CONTRACT','TJ','v1','AA==',1,1),('CONTRACT','TJ','v2','AA==',1,1) RETURNING id`)).rows;
      for(const r of [...rows,rows[0]])await db.query('SELECT activate_crm_document_template(1,$1)',[r.id]);
      const active=(await db.query('SELECT id FROM crm_document_templates WHERE active')).rows;expect(active).toHaveLength(1);expect(active[0].id).toBe(rows[0].id);
    }finally{await db.exec('RESET ROLE');}
  });
  it('does not expose the private trigger as an anonymous RPC',async()=>{
    const r=(await db.query(`SELECT has_schema_privilege('anon','tozon_internal','usage') AS allowed`)).rows[0];expect(r.allowed).toBe(false);
  });
});
